### ISSUE TITLE
doenst support the switch mini

### ISSUE THREAD

**Issue by robindelange** [ChristianGr1974/de.grewenig.zigbee#1]
thank you for making this app.

i installed the app on my homey, and It installed the switch mini quick, but when I push an button al the light go on. when I send a command with the app It says : missing capability listener:dim or on off. and nothing happens.

I think its not paired to homey , but light link

**Comment by ChristianGr1974** [comment]
Ok... not very clear what you try to do. The Mini Switch is not an actor, its a sensor. So from within the homey app you can't send any commands to the switch. That would not make any sense. The app purpose is to receive commands from the switch and execute one of the provided flows by the app.

**Comment by robindelange** [comment]
I know you cant send something to the switch.

When in pair my switch with homey, it doesnt work. The switch pair directly to other lights in my home. So when i press a button all the lamp will go on. ( light link?)

That makes the switch useless.
I have reset the switch many times, all the lights powered off. But that doesnt help, it keeps directly connecting to other lights instead of the homey.

Thank you for you help

Kind regards

Robin

Op 14 mei 2022 om 23:12 heeft Christian Grewenig ***@***.***> het volgende geschreven:

﻿

Ok... not very clear what you try to do. The Mini Switch is not an actor, its a sensor. So from within the homey app you can't send any commands to the switch. That would not make any sense. The app purpose is to receive commands from the switch and execute one of the provided flows by the app.

**Comment by robindelange** [comment]
hi christian, 

I tried it an other time, but the same thing happens before. did you read my last message?

**Comment by ChristianGr1974** [comment]
Hi…
yes i read read your message. But This is more an issue due to your infrastructure. I cannot support this, i have no other Osram actors running. 

The App is supposed to receive messages from the switch and to react to those via flows. 

Direct links in between your Osram products are not Part of This App.

kindly
Christian

**Comment by robindelange** [comment]
Christian,

I don’t have other Osram products, when I pair it with homey with your app it connects to all my lights, not to homey. The lights are from differend brands, like hue of Ikea but there is not an Osram product in the house except the switch itself.

I like to use it via homey with flows. But that doesn’t work

Greetz

Robin

Op 26 jun. 2022, om 15:43 heeft Christian Grewenig ***@***.******@***.***>> het volgende geschreven:



Hi…
yes i read read your message. But This is more an issue due to your infrastructure. I cannot support this, i have no other Osram actors running.

The App is supposed to receive messages from the switch and to react to those via flows.

Direct links in between your Osram products are not Part of This App.

kindly
Christian
